name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
        type: string
      release_name:
        description: 'Release Title'
        required: true
        type: string
      release_notes:
        description: 'Release Notes (leave blank to auto-generate)'
        required: false
        type: string

permissions:
  contents: write 

jobs:
  build-and-release:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

      - name: Build Executable
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name }}
          name: ${{ inputs.release_name }}
          body: ${{ inputs.release_notes }}
          files: ${{github.workspace}}/build/Release/docker-credential-antimeme.exe
          generate_release_notes: ${{ inputs.release_notes == '' }}
